name: MyMouseBattery
options:
  bundleIdPrefix: com.jmaudisio
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  developmentLanguage: es
  knownRegions:
    - es
    - en

settings:
  base:
    MARKETING_VERSION: "1.2"
    CURRENT_PROJECT_VERSION: "3"
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    PRODUCT_NAME: "$(TARGET_NAME)"
    ALWAYS_SEARCH_USER_PATHS: NO
  configs:
    release:
      DEBUG_INFORMATION_FORMAT: dwarf-with-dsym

targets:
  MyMouseBattery:
    type: application
    platform: macOS
    sources:
      - MyMouseBattery
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jmaudisio.MyMouseBattery
        INFOPLIST_FILE: MyMouseBattery/Info.plist
        CODE_SIGN_IDENTITY: "Apple Distribution"
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        CODE_SIGN_ENTITLEMENTS: MyMouseBattery/MyMouseBattery.entitlements
        COMBINE_HIDPI_IMAGES: YES
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: MyMouseBattery/Info.plist
      properties:
        CFBundleName: MyMouseBattery
        CFBundleDisplayName: My Mouse Battery
        CFBundleIdentifier: com.jmaudisio.MyMouseBattery
        CFBundleVersion: "3"
        CFBundleShortVersionString: "1.2"
        CFBundlePackageType: APPL
        CFBundleExecutable: MyMouseBattery
        LSMinimumSystemVersion: "14.0"
        LSUIElement: true
        LSApplicationCategoryType: public.app-category.utilities
        NSPrincipalClass: NSApplication
        NSHighResolutionCapable: true
        NSHumanReadableCopyright: "Copyright \u00a9 2026 JM Audisio. All rights reserved."
